In [11]:
import pandas as pd

#创建Data Frame的多种方式

df1 = pd.DataFrame(
    [
        {"name": "Alice", "age": 25},
        {"name": "Bob", "age": 30},
        {"name": "Charlie", "age": 35}
    ]
)
df1

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [10]:

df2 = pd.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie"],
        "age": [25, 30, 35]
    }
)
df2

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [8]:

df3 = pd.DataFrame(
    [
        ['Alice', 25],
        ['Bob', 30],
        ['Charlie', 35]
    ],
    columns=["name", "age"]
)
df3

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [12]:

df4 = pd.DataFrame(
    [
        ['Alice', 25],
        ['Bob', 30],
        ['Charlie', 35]
    ],
    columns=["name", "age"],
    index = ['a', 'b', 'c'],
)

df4

      name  age
a    Alice   25
b      Bob   30
c  Charlie   35

In [15]:
#DataFrame中的常见属性

#索引

# df4.index.tolist()

#列名

# df4.columns.tolist()

#值

# df4.values.tolist()

#元素个数

# df4.size

#数据类型

# df4.dtypes

#维度

df4.shape

Index(['name', 'age'], dtype='str')