In [4]:
import pandas as pd

#创建Data Frame的多种方式

df1 = pd.DataFrame(
    [
        {"name": "Alice", "age": 25},
        {"name": "Bob", "age": 30},
        {"name": "Charlie", "age": 35}
    ]
)
df1

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [5]:

df2 = pd.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie"],
        "age": [25, 30, 35]
    }
)
df2

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [6]:

df3 = pd.DataFrame(
    [
        ['Alice', 25],
        ['Bob', 30],
        ['Charlie', 35]
    ],
    columns=["name", "age"]
)
df3

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [20]:

df4 = pd.DataFrame(
    [
        ['Alice', 25],
        ['Bob', 30],
        ['Charlie', 35]
    ],
    columns=["name", "age"],
    index = ['a', 'b', 'c'],
)

df4

      name  age
a    Alice   25
b      Bob   30
c  Charlie   35

In [8]:
#DataFrame中的常见属性

#索引

# df4.index.tolist()

#列名

# df4.columns.tolist()

#值

# df4.values.tolist()

#元素个数

# df4.size

#数据类型

# df4.dtypes

#维度

df4.shape

(3, 2)

In [15]:
#series创建

s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [16]:
s2 = pd.Series((10,20,30,40,50),index = ['a','b','c','d','e'])
s2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [18]:
s3 = pd.Series({'a':10,'b':20,'c':30,'d':40,'e':50})
s3

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [23]:
s4 = df4['name']
s4

a      Alice
b        Bob
c    Charlie
Name: name, dtype: str

In [ ]:
#series常见属性

# s3.index.tolist() #索引
# s3.values.tolist() #值
# s3.size #元素个数
# s3.dtype #数据类型
# s3.shape #维度(行，列)